[package]
name = "macro_extern"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ext_proc = {path="ext_proc"}

[workspace]

members = [
 "ext_proc"
]

